"""del model_name

Revision ID: 6eb55170d9a8
Revises: da01cfd78c14
Create Date: 2025-06-27 07:16:16.235906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb55170d9a8'
down_revision = 'da01cfd78c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('model_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_name', sa.VARCHAR(length=64), nullable=False))

    # ### end Alembic commands ###
